title: "Felicia Jiang"
description: "Ph.D. candidate in medicine"
url: "https://feliciajiangbio.github.io"
baseurl: ""  # 根目录
repository: "FeliciaJiangBio/FeliciaJiangBio.github.io"

# 使用 GitHub Pages 默认兼容主题（可自定义）
remote_theme: "mmistakes/minimal-mistakes"

# 作者信息
author:
  name: "Felicia Jiang"
  avatar: "profile.png"
  bio: "Ph.D. candidate in medicine"
  location: "Shatin, Hong Kong"
  employer: "Chinese University of Hong Kong"
  uri: "https://feliciajiangbio.github.io/"
  email: "taojiangcuhk@gmail.com"
  github: "FeliciaJiangBio"
  googlescholar: "https://scholar.google.com/citations?user=_YT1sPQAAAAJ&hl=en&oi=sra"
  orcid: "https://orcid.org/0000-0001-8607-6804"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=tao+jiang"
  bluesky: "bsky.app"

# 使用白名单插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 使用这些插件需要同时 whitelisting
whitelist:
  - jekyll-feed
  - jekyll-sitemap

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM

# 输出设置
permalink: /:categories/:title/
timezone: "Etc/UTC"

# 其他页面设置
include:
  - _pages
  - 3DisoGalaxy

collections:
  teaching:
    output: true
  publications:
    output: true
  portfolio:
    output: true
  talks:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 压缩 HTML（可选）
compress_html:
  clippings: all
  ignore:
    envs: development
